server:
  port: 80
  tomcat:
    uri-encoding: utf-8

#spring:
#  mvc:
#    view:
#      prefix: /WEB-INF/jsp/
#      suffix: .jsp
logging:
  config: classpath:log4j2.xml

database:
  driverName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/springboot
  username: root
  password: 970712
